### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [MarzenaSz/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by MarzenaSz** [comment]
Hi Michael,

I added the mobile meta tag and set the row width to 100%.
It looks way better now but could still use some work here and there.
Thanks for pointing it out!

Let me know if this solves the issue :)

**Comment by Mikeysax** [comment]
Awesome ! :+1:
